development:
  adapter: postgresql
  database: rismay_dev
  host: localhost
  pool: 5
  timeout: 5000

# test:
#   adapter: postgresql
#   database: rismay_test
#   host: localhost
#   pool: 5
#   timeout: 5000
#
# production:
#   adapter: postgresql
#   database: rismay_prod
#   host: localhost
#   pool: 5
#   timeout: 5000
